# Generated by Django 3.2 on 2021-04-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210425_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_in_cents',
        ),
    ]
